from lib.common import *
from datetime import datetime
import pandas as pd

def run_health_check():
    logger = setup_logging("health_check")
    logger.info("Starting Daily Health Check Report")

    # Sample Data - You can replace with real SQL queries later
    data = {
        'Database': ['ORCL'],
        'Tablespace_Usage_%': [82.5],
        'ASM_Free_GB': [245],
        'DG_Lag_Minutes': [1],
        'Blocking_Sessions': [0],
        'Invalid_Objects': [12],
        'Long_Running_SQL': [3]
    }

    df = pd.DataFrame(data)

    html = f"""
    <h2>🛡️ Oracle DBA Daily Health Report</h2>
    <p><b>Report Date:</b> {datetime.now():%d-%b-%Y %H:%M:%S}</p>
    {df.to_html(index=False, border=1, classes='dataframe')}
    <hr>
    <p><b>Generated by:</b> Central DBA Automation Framework</p>
    """

    # Save Report
    report_file = f"reports/Health_Report_{datetime.now():%Y%m%d}.html"
    os.makedirs("reports", exist_ok=True)
    with open(report_file, 'w') as f:
        f.write(html)

    send_email("Daily Oracle Health Report", html)
    logger.info(f"Health Report generated: {report_file}")

if __name__ == "__main__":
    run_health_check()
